# STC Jawwy

In [1]:
"""
Here we install libraries that are not installed by default
Example:  pyslsb
Feel free to add any library you are planning to use.
"""
!pip install pyxlsb

Collecting pyxlsb
  Downloading pyxlsb-1.0.10-py2.py3-none-any.whl.metadata (2.5 kB)
Downloading pyxlsb-1.0.10-py2.py3-none-any.whl (23 kB)
Installing collected packages: pyxlsb
Successfully installed pyxlsb-1.0.10

In [2]:
# Import the required libraries
"""
Please feel free to import any required libraries as per your needs
"""
import pandas as pd     # provides high-performance, easy to use structures and data analysis tools
import pyxlsb           # Excel extention to read xlsb files (the input file)
import numpy as np      # provides fast mathematical computation on arrays and matrices

# Jawwy dataset
The dataset consists of details about each customer and the movies and/or tv shows watched in addition to the genre.

You are required to work on task three to build a recommendation engine for our platform to Recommend movies to usesrs that they might be interested in¶

In [4]:
dataframe = pd.read_excel("stc- Jawwy TV Data Set_T3.xlsb",index_col=0)
# Please make a copy of dataset if you are going to work directly and make changes on the dataset
# you can use   df=dataframe.copy()

In [5]:
# check the data shape
dataframe.shape

(1048575, 5)

In [6]:
# display the first 5 rows
dataframe.head()

   user_id_maped          program_name  rating      date_ program_genre
0          26138            100 treets       1 2017-05-27         Drama
1           7946                 Moana       1 2017-05-21     Animation
2           7418  The Mermaid Princess       1 2017-08-10     Animation
3          19307  The Mermaid Princess       2 2017-07-26     Animation
4          15860             Churchill       2 2017-07-07     Biography

In [7]:
# describe the numeric values in the dataset
dataframe.describe()

       user_id_maped        rating                          date_
count   1.048575e+06  1.048575e+06                        1048575
mean    1.709266e+04  2.497283e+00  2017-10-04 00:23:20.346183936
min     1.000000e+00  1.000000e+00            2017-03-14 00:00:00
25%     8.253000e+03  1.000000e+00            2017-06-10 00:00:00
50%     1.714900e+04  2.000000e+00            2017-10-14 00:00:00
75%     2.566500e+04  3.000000e+00            2018-01-21 00:00:00
max     3.428000e+04  4.000000e+00            2018-04-30 00:00:00
std     1.003513e+04  1.119837e+00                            NaN

In [8]:
# check if any column has null value in the dataset
dataframe.isnull().any()

user_id_maped    False
program_name     False
rating           False
date_            False
program_genre    False
dtype: bool

In [9]:
# we import Visualization libraries
# you can ignore and use any other graphing libraries
import matplotlib.pyplot as plt # a comprehensive library for creating static, animated, and interactive visualizations
import plotly #a graphing library makes interactive, publication-quality graphs. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [15]:
dataframe.columns

Index(['user_id_maped', 'program_name', 'rating', 'date_', 'program_genre'], dtype='object')

In [16]:
dataframe.head()

   user_id_maped          program_name  rating      date_ program_genre
0          26138            100 treets       1 2017-05-27         Drama
1           7946                 Moana       1 2017-05-21     Animation
2           7418  The Mermaid Princess       1 2017-08-10     Animation
3          19307  The Mermaid Princess       2 2017-07-26     Animation
4          15860             Churchill       2 2017-07-07     Biography

In [17]:
dataframe["rating"].value_counts()

rating
1    264293
4    262113
3    261505
2    260664
Name: count, dtype: int64

In [20]:
print(dataframe.columns.tolist())

['user_id_maped', 'program_name', 'rating', 'date_', 'program_genre']

In [21]:
print(dataframe.shape)

(1048575, 5)

In [10]:
"""
TODO build your Recommender system to Highlight Programs that usesrs might be interested in
"""

'\nTODO build your Recommender system to Highlight Programs that usesrs might be interested in\n'

In [24]:
dataframe[dataframe["program_name"].astype(str).str.contains("Moana", case=False, na=False)]["program_name"].unique()

array(['Moana'], dtype=object)

In [26]:
moana_data = dataframe[dataframe["program_name"] == "Moana"]

moana_data.head()

     user_id_maped program_name  rating      date_ program_genre
1             7946        Moana       1 2017-05-21     Animation
18           26546        Moana       1 2017-06-25     Animation
19           20306        Moana       1 2017-06-23     Animation
48           28687        Moana       2 2017-05-30     Animation
191          16739        Moana       1 2017-05-27     Animation

In [30]:
dataframe[dataframe["program_name"] == "Moana"]["user_id_maped"].head()

1       7946
18     26546
19     20306
48     28687
191    16739
Name: user_id_maped, dtype: int64

In [11]:
"""
TODO show the recommendations (top 5) for the people who watched "Moana" movie
"""

'\nTODO show the recommendations (top 5) for the people who watched "Moana" movie\n'

In [33]:
moana_recommendations = dataframe[
    dataframe["user_id_maped"].isin(
        dataframe.loc[
            dataframe["program_name"] == "Moana",
            "user_id_maped"
        ]
    )
]

moana_recommendations = (
    moana_recommendations[
        moana_recommendations["program_name"] != "Moana"
    ]
    .groupby("program_name")["rating"]
    .mean()
    .sort_values(ascending=False)
    .head(5)
)

moana_recommendations

program_name
The Tudors     Lady In Waiting                                         4.0
The Penguins of Madagascar  I Was A Penguin Zombie / ting Operation    4.0
The Penguins of Madagascar  An Elephant Never Forgets                  4.0
House of Lies     Our Descent Into Los Angeles                         4.0
House of Lies     Business                                             4.0
Name: rating, dtype: float64

In [34]:
recommendation_sample = moana_recommendations.reset_index()
recommendation_sample.columns = ["Recommended_Program", "Average_Rating"]

recommendation_sample

                                 Recommended_Program  Average_Rating
0                     The Tudors     Lady In Waiting             4.0
1  The Penguins of Madagascar  I Was A Penguin Zo...             4.0
2  The Penguins of Madagascar  An Elephant Never ...             4.0
3     House of Lies     Our Descent Into Los Angeles             4.0
4                         House of Lies     Business             4.0