# STC Jawwy

In [1]:
"""
Here we install libraries that are not installed by default
Example:  pyslsb
Feel free to add any library you are planning to use.
"""
!pip install pyxlsb

Requirement already satisfied: pyxlsb in /usr/local/lib/python3.12/dist-packages (1.0.10)

In [2]:
# Import the required libraries
"""
Please feel free to import any required libraries as per your needs
"""
import pandas as pd     # provides high-performance, easy to use structures and data analysis tools
import pyxlsb           # Excel extention to read xlsb files (the input file)
import numpy as np      # provides fast mathematical computation on arrays and matrices

# Jawwy dataset
The dataset includes total watching hours for customers per day.

You are required to work on predecting the forecast for the watching hours.

In [3]:
dataframe = pd.read_excel("stc- Jawwy TV Data Set_T2.xlsb",index_col=0)
# Please make a copy of dataset if you are going to work directly and make changes on the dataset
# you can use   df=dataframe.copy()

In [4]:
# check the data shape
dataframe.shape

(86, 2)

In [5]:
# display the first 5 rows
dataframe.head()

       date_  Total_watch_time_in_houres
0 2018-01-01                 1123.551944
1 2018-01-02                 1000.129722
2 2018-01-03                  881.924444
3 2018-01-04                  782.669444
4 2018-01-05                 1051.939444

In [6]:
# display the dataset after applying data types
dataframe.head()

       date_  Total_watch_time_in_houres
0 2018-01-01                 1123.551944
1 2018-01-02                 1000.129722
2 2018-01-03                  881.924444
3 2018-01-04                  782.669444
4 2018-01-05                 1051.939444

In [7]:
# describe the numeric values in the dataset
dataframe.describe()

                               date_  Total_watch_time_in_houres
count                             86                   86.000000
mean   2018-02-28 17:01:23.720930304                  780.817926
min              2018-01-01 00:00:00                  562.124722
25%              2018-01-30 06:00:00                  707.709653
50%              2018-02-28 12:00:00                  763.181389
75%              2018-03-29 18:00:00                  840.985278
max              2018-04-30 00:00:00                 1123.551944
std                              NaN                  122.992002

In [8]:
# check if any column has null value in the dataset
dataframe.isnull().any()

date_                         False
Total_watch_time_in_houres    False
dtype: bool

In [9]:
# we import Visualization libraries
# you can ignore and use any other graphing libraries
import matplotlib.pyplot as plt # a comprehensive library for creating static, animated, and interactive visualizations
import plotly #a graphing library makes interactive, publication-quality graphs. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [10]:
# Setting the date as index
dataframe.set_index('date_', inplace=True)

In [11]:
# Display the dataframe after setting the date as index
dataframe.head()

            Total_watch_time_in_houres
date_
2018-01-01                 1123.551944
2018-01-02                 1000.129722
2018-01-03                  881.924444
2018-01-04                  782.669444
2018-01-05                 1051.939444

In [12]:
# show the dataframe
fig = px.line(dataframe,  y="Total_watch_time_in_houres")
fig.show()

In [ ]:
"""
TODO using the previous dataset (df) build a prediction model to predict the expected watch time for the next two months
Hint: you can build a forecast model to predict the results
"""

'\nTODO using the previous dataset (df) build a prediction model to predict the expected watch time for the next two months\nHint: you can build a forecast model to predict the results\n'

In [14]:
df=pd.read_excel("stc- Jawwy TV Data Set_T2.xlsb")
#

In [15]:
df.columns

Index(['Unnamed: 0', 'date_', 'Total_watch_time_in_houres'], dtype='object')

In [16]:
df["date_"]=pd.to_datetime(df["date_"])

In [17]:
monthly_watch = df.groupby(df["date_"].dt.to_period("M"))["Total_watch_time_in_houres"].sum()

monthly_watch

date_
2018-01    19931.016111
2018-02    16469.292500
2018-03    16602.283333
2018-04    14147.749722
Freq: M, Name: Total_watch_time_in_houres, dtype: float64

In [18]:
monthly_watch.index = monthly_watch.index.to_timestamp()

monthly_watch

date_
2018-01-01    19931.016111
2018-02-01    16469.292500
2018-03-01    16602.283333
2018-04-01    14147.749722
Freq: MS, Name: Total_watch_time_in_houres, dtype: float64

In [19]:
len(monthly_watch)

4

In [20]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

model = ExponentialSmoothing(monthly_watch, trend="add")
fit = model.fit()

forecast = fit.forecast(2)

forecast

2018-05-01    12483.384940
2018-06-01    10761.704844
Freq: MS, dtype: float64

In [21]:
forecast_df = forecast.reset_index()
forecast_df.columns = ["Date", "Predicted_Watch_Time_in_Hours"]

forecast_df

        Date  Predicted_Watch_Time_in_Hours
0 2018-05-01                   12483.384940
1 2018-06-01                   10761.704844

In [22]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=monthly_watch.index,
    y=monthly_watch.values,
    mode="lines+markers",
    name="Actual Watch Time"
))

fig.add_trace(go.Scatter(
    x=forecast.index,
    y=forecast.values,
    mode="lines+markers",
    name="Forecast"
))

fig.update_layout(
    title="Watch Time Forecast for the Next Two Months",
    xaxis_title="Date",
    yaxis_title="Watch Time in Hours"
)

fig.show()

Finding:

A forecasting model was built using the historical monthly watch time data.
The model predicts the expected total watch time for the next two months based on the previous viewing pattern.

The forecast results are shown in the table and visualization above.